### ISSUE TITLE
repo not found

### ISSUE THREAD

**Issue by MarceVera** [hyp1231/AmazonReviews2023#10]
Hi, I was unable to download the metadata from the links provided, the urls were not found. Would you please fix the issue?

**Comment by hyp1231** [comment]
Hi, thanks for bringing this issue to our attention! We will fix it soon.

Before that, you can download the data from [Hugging Face Hub](https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023) instead, which contains that same copy of data.
