### ISSUE TITLE
Empty description in dataset-reg.

### ISSUE THREAD

**Issue by sankar589** [hyp1231/AmazonReviews2023#16]
The dataset only has an empty column of description while it was supposed to have a detailed description of the product in the metadata of the product. Kindly update the dataset for better use of this in training a recommender system.

**Comment by hyp1231** [comment]
For most items on Amazon.com, metadata is distributed across several fields, including `title`, `description`, `features`, and `details`. Some of these fields may often be empty. It’s common for an item’s description to be missing. You can also check the product webpage to see if a description is available there. If you come across multiple items with descriptions on their webpage but an empty description field in the dataset, please let me know. Thank you!

For model training, I recommend merging all these fields, as we can’t always anticipate which ones may be empty.
