### ISSUE TITLE
Issue with Model Checkpoint for BLaIR / Reproducing Results

### ISSUE THREAD

**Issue by Sooyonglee** [hyp1231/AmazonReviews2023#17]
I am trying to download the model checkpoint for blair-roberta-base (as well as blair-roberta-large) but am running into a 404 Client Error: Not Found for url: https://huggingface.co/hyp1231/blair-roberta-base/resolve/main/pytorch_model.bin when running the following line of code:
`model = AutoModel.from_pretrained("hyp1231/blair-roberta-base")`

I would appreciate some help with this as I am interested in reproducing the results found in table 4 in the paper. Can you share the code used for evaluating the models? I was not able to find it in the repo.

**Comment by hyp1231** [comment]
Hi! Thanks for your interest in our work. For reproducing the results in Table 4, please refer to the scripts provided here: https://github.com/hyp1231/AmazonReviews2023/blob/main/seq_rec_results/README.md.

If you encounter any issues loading the model with these scripts, could you let me know the versions of your `transformers` and `datasets` packages? Thanks!

**Comment by Sooyonglee** [comment]
Thank you for the response, I'm now able to use the model checkpoint for the BLAIR model. I'm wondering if you have any plans on releasing information about the prompts that were used to generate the queries for the c4 dataset?
