### ISSUE TITLE
Query regarding evaluation of ESCI and Amazon C4 dataset

### ISSUE THREAD

**Issue by vishal1383** [hyp1231/AmazonReviews2023#19]
Hi, thanks a lot for the repo!. I had a couple of clarifying questions on how evaluation is done for the ESCI dataset.

 1.  In table 8 and 9 of the paper [Bridging Language and Items for Retrieval and Recommendation](https://arxiv.org/pdf/2403.03952)  what is the metric reported for the ESCI dataset (if I understand correctly, it is R@10). 

2. Is the full test split of ESCI huggingface dataset (containing 638k test examples) used for evaluation, if not then is the test dataset published somewhere (as I believe the paper mentions some timestamp filtering is also done).

3. For the AmazonC4 dataset do you also have product image-urls available for each product id? I tried to check the raw_meta_category dataset in McAuley-Lab/Amazon-Reviews-2023 for product ids in the C4 dataset to get product image urls and it seems that product ids are disjoint in both datasets. Is this on purpose? and if possible is there a way I can get the product image urls for Amazon C4 dataset.

**Comment by hyp1231** [comment]
Hi, thank you for your interest in our work!

Re Q1: We report the NDCG@100 metric, which is consistent with what we used in Table 7.

Re Q2: We will release the data processing script and the processed evaluation set of ESCI shortly.

Re Q3: The product IDs in Amazon C4 should exist in the Amazon Reviews dataset. However, note that not all items have associated product images. For those that do, the corresponding URLs are highly likely to exist in the dataset. By saying "product IDs are disjoint in both datasets", do you mean that none of the products in Amazon C4 appear in Amazon Reviews 2023?

**Comment by vishal1383** [comment]
Hi, thanks a lot! for your response. For Q3 I've noticed that the product_id in Amazon C4 and ones present in Amazon Reviews product metadata don't seem to match (I was checking the full split). I get that some products might not have images, but I am noticing that none of the product ids in C4 are present in AmazonReviews product metadata. If this is not expected I might be doing some wrong.

**Comment by vishal1383** [comment]
Hi @hyp1231 can you please help me out with this. I had an additional question, in table it is said that NDCG@100 metric is reported, but I see some values >1, or is one row R@100 and the other NDCG@100?

**Comment by hyp1231** [comment]
Hi @vishal1383,

For Q2, the numbers we reported are nDCG@100 (scaled by 100) to avoid overly small values like 0.00. We’ll clarify this in the next version.

For Q3, I’ll check the details and get back to you about whether there are any disjoint product IDs.

**Comment by hyp1231** [comment]
**[update]**

We have just uploaded the processed ESCI dataset, along with the data processing code and the code needed to reproduce results on the ESCI dataset.

https://github.com/hyp1231/AmazonReviews2023/tree/main/product_search_results

**Comment by vishal1383** [comment]
Hi @hyp1231 thanks a lot! I'll check this out, if you get any more details on disjoint product ids between amazon c4 and amazon reviews, please let me know.

**Comment by vishal1383** [comment]
Hi @hyp1231, I had a question, as you mentioned in table 9 nDCG@100 numbers are multiplied by 100, is the case same for table 8 (i.e. 0.005 is the NDCG@100 for Amazon C4 on all domains).
<img width="637" alt="Screenshot 2024-12-17 192910" src="https://github.com/user-attachments/assets/ef41e16c-1cda-4f92-aed0-0ee69332e169" />

**Comment by hyp1231** [comment]
Hi @vishal1383, yes, the case is the same for table 8.

**Comment by vishal1383** [comment]
thank you for confirming!
