### ISSUE TITLE
Where is ReviewerName attribute ?

### ISSUE THREAD

**Issue by DudiArbiv** [hyp1231/AmazonReviews2023#2]
Thanks you for the new dataset
Does the new 2023 dataset missing ReviewerName attribute ?

**Comment by hyp1231** [comment]
Thanks for your interest!

Indeed, the ReviewerName attribute is not included in the new dataset. We did not find it significantly helpful for recommender system research (but raised some privacy concerns). If this attribute is specifically important for your study, please let us know.
