### ISSUE TITLE
Blair folder is missing: feature or a bug?

### ISSUE THREAD

**Issue by AnastasiiaShukhova** [hyp1231/AmazonReviews2023#5]
Hi, I wanted to look into the code for the BLAIR implementation, but the entire blair folder seems to be empty. Is it supposed to be empty? If yes, where would I find the implementation code?

**Comment by hyp1231** [comment]
Hi, thanks for your interest! We've just uploaded the checkpoints, data processing scripts, and training scripts in [`blair/`](https://github.com/hyp1231/AmazonReviews2023/tree/main/blair). Please do not hesitate to contact me if you find any issues.

**Comment by AnastasiiaShukhova** [comment]
Thank you!
