### ISSUE TITLE
BLAIR hugging face model

### ISSUE THREAD

**Issue by marcv12** [hyp1231/AmazonReviews2023#6]
I was wondering if you will release the BLAIR model on Hugging Face soon because I believe the benchmark improvements is considerable and further fine-tuning could lead to even better performance. Please let me know if this is the case

**Comment by hyp1231** [comment]
Hi, thanks for your interest and patience!

We have just released the checkpoints on HuggingFace.
* [blair-roberta-base](https://huggingface.co/hyp1231/blair-roberta-base) (125M)
* [blair-roberta-large](https://huggingface.co/hyp1231/blair-roberta-large) (355M)
