### ISSUE TITLE
BLAIR integration with UniSrec

### ISSUE THREAD

**Issue by marcv12** [hyp1231/AmazonReviews2023#8]
Could you also kindly publish the code for integrating BLAIR with UniSrec because from what I see this is not available at the moment. This helps a lot with reproducibility! Thanks!

**Comment by hyp1231** [comment]
Sure, of course. I'll upload the corresponding code as soon as possible.

**Comment by marcv12** [comment]
Any update in that regards?

**Comment by hyp1231** [comment]
Hi sorry for the delay. I've uploaded the code for integrating BLaIR with UniSRec for sequential recommendation 1d25997. The code is available at [seq_rec_results](https://github.com/hyp1231/AmazonReviews2023/tree/main/seq_rec_results).
